version: "3.9"

services:
  mongo:
    image: mongo:8.0.9-noble
    container_name: mongo-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mernapp
    volumes:
      - mongo_data:/data/db
    networks:
      - mernapp-net
    restart: unless-stopped

  backend:
    build: ./node
    container_name: node-container
    ports:
      - "5000:5000"
    environment:
      MONGO_URL: mongodb://mongo-container:27017/mernapp
    depends_on:
      - mongo
    networks:
      - mernapp-net
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: react-container
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mernapp-net
    restart: unless-stopped

volumes:
  mongo_data:

networks:
  mernapp-net:
    driver: bridge

